### ISSUE TITLE
Plist is missing.

### ISSUE THREAD

**Issue by dimitrihamelin** [google/GoogleAppMeasurement#65] opened 2024-03-06 20:58 UTC
The bundle 'Payload/StarME.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: 26655415-6523-45f1-8353-3b78af719cce)

**Comment by ncooke3** [comment] 2024-03-06 21:01
Thanks, this is a duplicate of #62. We are working on a patch release to fix this issue. Please follow https://github.com/firebase/firebase-ios-sdk/issues/12441 for updates!

**Comment by dimitrihamelin** [comment] 2024-03-06 21:01
Thank you so much.

**Closed by ncooke3** 2024-03-06 21:01 UTC
